apiVersion: v1
kind: Secret
metadata:
  name: automation-runner-secrets
  namespace: sqa
type: Opaque
stringData:
  MOTIVE_ADMIN_EMAIL: "<set-me>"
  MOTIVE_ADMIN_PASSWORD: "<set-me>"
  MOTIVE_WEBUSERNAMEPASSWORD: "<set-me>"
  MOTIVE_ADMIN_CONSOLE_EMAIL: "<set-me>"
  MOTIVE_ADMIN_CONSOLE_PASSWORD: "<set-me>"
  MOTIVE_DRIVER_EMAIL: "<set-me>"
  MOTIVE_DRIVER_PASSWORD: "<set-me>"
  MOTIVE_ELDAPIKEY_STAGING: "<set-me>"
  MOTIVE_MOBILEAPIAUTHORIZATIONKEY: "<set-me>"
  MOTIVE_TESTING_API_KEY_STAGING: "<set-me>"
  MOTIVE_INTERNAL_API_KEY_STAGING: "<set-me>"
  MOTIVE_AI_DRIVER_EMAIL_ID: "<set-me>"
  MOTIVE_AI_DRIVER_PASSWORD: "<set-me>"
  MOTIVE_AI_VEHICLE_ID: "<set-me>"
  MOTIVE_AI_ELD_DEVICE_ID: "<set-me>"
  MOTIVE_AI_ELD_IDENTIFIER: "<set-me>"
  MOTIVE_CAMERA_SERIALNUMBER: "<set-me>"
  MOTIVE_SAFETY1_DRIVER_ID: "<set-me>"
  MOTIVE_SAFETY1_VEHICLE_ID: "<set-me>"
  MOTIVE_SAFETY1_ELD_DEVICE_ID: "<set-me>"
  MOTIVE_SAFETY1_ELD_IDENTIFIER: "<set-me>"
  MOTIVE_SAFETY1_DRIVER_EMAIL_ID: "<set-me>"
  MOTIVE_SAFETY1_DRIVER_PASSWORD: "<set-me>"
  MOTIVE_SAFETY2_DRIVER_ID: "<set-me>"
  MOTIVE_SAFETY2_VEHICLE_ID: "<set-me>"
  MOTIVE_SAFETY2_ELD_DEVICE_ID: "<set-me>"
  MOTIVE_SAFETY2_ELD_IDENTIFIER: "<set-me>"
  MOTIVE_SAFETY2_DRIVER_EMAIL_ID: "<set-me>"
  MOTIVE_SAFETY2_DRIVER_PASSWORD: "<set-me>"
  MOTIVE_DC54_VEHICLE_NUMBER: "<set-me>"
  MOTIVE_OC_VEHICLE_NUMBER: "<set-me>"
  MOTIVE_OC_IDENTIFIER: "<set-me>"
  MOTIVE_EXEMPTDRIVERWITHVEHICLE_OCVEHICLEID: "<set-me>"
  MOTIVE_EXEMPTDRIVERWITHVEHICLE_OCELDDEVICEID: "<set-me>"
  AWS_ACCESS_KEY_ID: "<optional-if-needed>"
  AWS_SECRET_ACCESS_KEY: "<optional-if-needed>"
  AWS_SESSION_TOKEN: "<optional-if-needed>"
